console.log('WELCOME TO ORANGE')
console.log('TO')
console.log('Hello ' + 'from ' + 'Orange')
console.log('wlcome to orange')
console.log('17')
console.log("Welcome to 'Orange'")
console.log('Welcome to Orange Jordan')